threesquare/config/routes.rb
Threesquare::Application.routes.draw do
  
  root 'locations#landing_page'
  resources :locations
   
end

threesquare/app/models/location.rb
class Location < ActiveRecord::Base
	validates :name, :picture_url, presence: true

	def snippet
		self.review.truncate(50)
	end
	
end

threesquare/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

threesquare/app/controllers/locations_controller.rb
class LocationsController < ApplicationController
	
	def landing_page
	end

	def show
		@location = Location.find(params[:id])
	end

	def index
		@locations = Location.all
	end

	def new
		@location = Location.new
	end

	def create
		@location = Location.new(location_params)
		@location.save

		# After creating a new location review,
		# redirect to see newly created review
		redirect_to location_path(@location)
	end

	def edit
		@location = Location.find(params[:id])
	end

	def update
		@location = Location.find(params[:id])
		@location.update(location_params)
		
		# After editing a location review,
		# redirect to see newly edited review
		redirect_to location_path(@location) 
	end

	def destroy
		@location = Location.find(params[:id])
		@location.destroy

		redirect_to	locations_path
	end

	private
	def location_params
		params.require(:location).permit(:name, :picture_url, :review)
	end

end

threesquare/app/helpers/application_helper.rb
module ApplicationHelper
end

threesquare/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Threesquare</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

threesquare/app/views/locations/_form.html.erb
<%= form_for @location do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
<br>
  <%= f.label :picture_url %>
  <%= f.text_field :picture_url %>
<br>
  <%= f.label :review %>
  <%= f.text_field :review %>
<br>
  <%= f.submit %>
<% end %>

threesquare/app/views/locations/edit.html.erb
<h2>Edit Location Review</h2>

<%= render "form" %>

threesquare/app/views/locations/index.html.erb
<button><%= link_to "Home", root_url %></button>

<h1>Location Reviews</h1>

<table>
  <thead>
    <tr>
      <th style="text-align:left">Location</th>
      <th style="text-align:left">Review Snippet</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |loc| %>
      <tr>
        <td><%= loc.name %>&nbsp;</td>
        <td><%= loc.snippet %>&nbsp;</td>
        <td><%= link_to 'Show Review', loc %>&nbsp;</td>
        <td><%= link_to 'Edit Review', edit_location_path(loc) %>&nbsp;</td>
        <td><%= link_to 'Delete Review', loc, method: :delete, data: { confirm: "Are you sure you want to delete the review for #{loc.name}?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p><button><%= link_to "Create New Review", new_location_path %></button></p>

threesquare/app/views/locations/landing_page.html.erb
<head>
	<title>3square</title>
</head>

<body>
	<h1><%= link_to "Welcome to 3square", locations_path %></h1>
</body>

threesquare/app/views/locations/new.html.erb
<h2>Create a New Location Review</h2>

<%= render "form" %>

threesquare/app/views/locations/show.html.erb
<button><%= link_to "Home", root_url %></button>
<button><%= link_to "Back to Reviews", locations_path %></button>

<h1><%= @location.name %></h1>

<h3>Location Review:</h3>
<p><%= @location.review %></p>
<p><button><%= link_to "Edit Review", edit_location_path(@location) %></button></p>

<img src="<%= @location.picture_url %>" height=300px width=400px>